name: clasp deploy

on:
    push:
        branches: ["master"]

jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: clasp

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Clasp Action
              uses: FieryRMS/clasp-action@v1.1.1
              with:
                  accessToken: ${{ secrets.ACCESS_TOKEN }}
                  idToken: ${{ secrets.ID_TOKEN }}
                  refreshToken: ${{ secrets.REFRESH_TOKEN }}
                  clientId: ${{ secrets.CLIENT_ID }}
                  clientSecret: ${{ secrets.CLIENT_SECRET }}
                  scriptId: ${{ secrets.SCRIPT_ID }}
                  command: "deploy"
                  deployId: ${{ secrets.DEPLOY_ID }}
                  description: "Github Actions: clasp deploy"
